### ISSUE TITLE
Revisión Mercado Liebre

### ISSUE THREAD

**Issue by lucianafigueroa** [decimechochi/Mercadoliebre.render#1]
[] 1- El main cumple, el header cumple en el home y en login pero en creá tu cuenta no y el footer cumple en todas las secciones.
[] 2- a) Cumple b) No cumple el margen inferior de separación de 10 píxeles.
[] 3- Cumple.
[] 4- Cumple.
[] 5- Cumple.
[] 6- No Cumple.
[] 7- Cumple en el home pero en el login y en creá tu cuenta no.
[] 8- Si cumple con la transición del camión pero falta la transición que se genera al posicionar el puntero en el articulo.
[] 9- Me gustó la estructura del registro de usuario en creá tu cuenta y los colores utilizados ya que combinan con la paleta. Destaco el esfuerzo de Ro ya que al no tener conocimientos previos cuesta más.
[] 10- Lo que considero que se podría mejorar es el tamaño del footer en el home (lo haría un poco más grande) y la estructura del Iniciar Sesión la haría también un poco más grande ya que en versión desktop se ve pequeño.

**Comment by decimechochi** [comment]
Hola Lu! realice modificaciones en la pagina. podrias revisarlo porfa para ver que me falta?.
Gracias desde ya!
