### ISSUE TITLE
Issue en Mercado-Liebre

### ISSUE THREAD

**Issue by Florsecco** [decimechochi/Mercadoliebre.render#2]
- [] 1 - Cumple en las dos vistas, excepto en la vista de Crea tu Cuenta que falta la barra de navegacion y la de busqueda:
![image](https://github.com/decimechochi/Mercadoliebre.render/assets/146774903/648b1f9d-585b-4e56-8c1d-9138761b2c14)
- [] 2 - Cumple el tamaño pero falta el margen inferior de 10 px
![image](https://github.com/decimechochi/Mercadoliebre.render/assets/146774903/0c80c632-e20f-4013-93ee-129c7737cdd3)
- [] 3 - Cumple
- [] 4 - Cumple
- [] 5 - Cumple
- [] 6 - No cumple
- [] 7 - Cumple en home, pero en login no
- [] 8 - Cumple la transicion del carrito pero falta la propiedad que da sombra a los articulos cuando se hace hover y la que hace aparecer la descripcion del producto al hacer hover.
- [] 9 - Me parecen muy acertada la adaptabilidad a las distintas resoluciones, me gusta mucho el formato elegido de la fuente ya que se hace muy claro de leer.
- [] 10 - Considero que se podria cambiar el footer para que no sea una caja con sombra, sino que sea una seccion mas similar al header, y tambien en la resoluciones de tablets en adelante haria que tengan display flex row el logo, la barra de busqueda y el "compra en cuotas..."
![image](https://github.com/decimechochi/Mercadoliebre.render/assets/146774903/1a7edb93-0715-4669-a439-be0aa4954497)
![image](https://github.com/decimechochi/Mercadoliebre.render/assets/146774903/03a9c3ad-2e75-465a-9890-f065e20bc8ce)

**Comment by decimechochi** [comment]
Hola flor! realice actualizaciones en la pagina. podrias revisarlo porfa?.
Gracias!
